// This file is "model.dart"
import 'package:dart_mappable/dart_mappable.dart';
import 'package:rifq/features/owner_flow/profile/domain/entities/user_profile_entity.dart';

import '../../domain/entity/pet_profile_entity.dart';

// Will be generated by dart_mappable
part 'pet_profile_model.mapper.dart';

@MappableClass()
class PetProfileModel extends PetProfileEntity with PetProfileModelMappable {
 PetProfileModel({
   @MappableField(key: 'pet_id') required super.id,
   @MappableField(key: 'pet_name') required super.name,
   @MappableField(key: 'pet_breed')required super.breed,
   @MappableField(key: 'pet_species') required super.species,
   @MappableField(key: 'pet_birthdate')required super.birthdate,
   @MappableField(key: 'pet_photo') required super.photoUrl,
  @MappableField(key: 'owner_id') required super.ownerId,
   @MappableField(key: 'pet_gender') required super.gender,
  @MappableField(key: 'pet_created_at')required super.createdAt});
}