// المودل مختتتتلف عن مودل الحيوانات اللي تحت لان هنا اعمده ثانيه احتاجها
import 'package:dart_mappable/dart_mappable.dart';
import '../../../../../../../core/shared/enum/status_booking_enum.dart';
import '../../domain/entity/booking_hotel_entity.dart';

// Will be generated by dart_mappable
part 'booking_hotel_model.mapper.dart';

@MappableClass()
class BookingHotelModel extends BookingHotelEntity with BookingHotelModelMappable {
  BookingHotelModel({
    required super.id,
    @MappableField(key: 'user_id') required super.userId,
    @MappableField(key: 'provider_id')required super.providerId,
    @MappableField(key: 'service_type_id') required super.serviceTypeId,
    @MappableField(key: 'service_item_id') required super.serviceItemId,
    @MappableField(key: 'pet_id') required super.petId,
    @MappableField(key: 'start_date') required super.startDate,
    @MappableField(key: 'end_date') required super.endDate,
    required super.status,
    required super.notes,
    @MappableField(key: 'created_at')required super.createdAt,
  });

  factory BookingHotelModel.fromEntity(BookingHotelEntity entity) {
    return BookingHotelModel(
      id: entity.id,
      userId: entity.userId,
      providerId: entity.providerId,
      serviceTypeId: entity.serviceTypeId,
      serviceItemId: entity.serviceItemId,
      petId: entity.petId,
      startDate: entity.startDate,
      endDate: entity.endDate,
      status: entity.status,
      notes: entity.notes,
      createdAt: entity.createdAt,
    );
  }

  BookingHotelEntity toEntity() {
    return BookingHotelEntity(
      id: id,
      userId: userId,
      providerId: providerId,
      serviceTypeId: serviceTypeId,
      serviceItemId: serviceItemId,
      petId: petId,
      startDate: startDate,
      endDate: endDate,
      status: status,
      notes: notes,
      createdAt: createdAt,
    );
  }
}

