// المودل مختتتتلف عن مودل الحيوانات اللي تحت لان هنا اعمده ثانيه احتاجها
import 'package:dart_mappable/dart_mappable.dart';
import '../../../../../pet_profile/sup_features/pet_info_card/domain/entity/pet_entity.dart';
import '../../domain/entity/pet_entity.dart';

// Will be generated by dart_mappable
part 'pet_profiel_model.mapper.dart';

@MappableClass()
class PetProfileModel extends PetProfileEntity with PetProfileModelMappable {
  // الخصائص الإضافية للـ Data Layer فقط
  final String? ownerAuthId;
  final String? ownerName;
  final String? ownerEmail;

  PetProfileModel({
    required super.id,
    required super.name,
    required super.breed,
    required super.species,
    required super.birthdate,
    required super.photoUrl,
    required super.ownerId,
    required super.gender,
    required super.createdAt,
    this.ownerAuthId,
    this.ownerName,
    this.ownerEmail,
  });

  /// تحويل Entity → Model
  factory PetProfileModel.fromEntity(PetProfileEntity entity) {
    return PetProfileModel(
      id: entity.id,
      name: entity.name,
      breed: entity.breed,
      species: entity.species,
      birthdate: entity.birthdate,
      photoUrl: entity.photoUrl,
      ownerId: entity.ownerId,
      gender: entity.gender,
      createdAt: entity.createdAt,
      ownerAuthId: null,
      ownerName: null,
      ownerEmail: null,
    );
  }

  /// تحويل Model → Entity (تجاهل الخصائص الإضافية)
  PetProfileEntity toEntity() {
    return PetProfileEntity(
      id: id,
      name: name,
      breed: breed,
      species: species,
      birthdate: birthdate,
      photoUrl: photoUrl,
      ownerId: ownerId,
      gender: gender,
      createdAt: createdAt,
    );
  }
}
