// This file is "model.dart"
import 'package:dart_mappable/dart_mappable.dart';
import 'package:rifq/features/owner_flow/ai/domain/entity/ai_message_entity.dart';

// Will be generated by dart_mappable
part 'ai_model.mapper.dart';

@MappableClass()
class AIModel extends AIEntity with AIModelMappable {
  AIModel({required String apiKey, required String model, required String instructions, required String welcomeMessage}) : super (apiKey: apiKey, model: model, instructions: instructions, welcomeMessage: welcomeMessage);

}