// This file is "model.dart"
import 'package:dart_mappable/dart_mappable.dart';
import 'package:rifq/features/owner_flow/ai/domain/entity/ai_message_entity.dart';

// Will be generated by dart_mappable
part 'ai_model.mapper.dart';

@MappableClass()
class AIModel extends AIEntity with AIModelMappable {
  AIModel({
    required super.apiKey,
    required super.model,
    required super.instructions,
    required super.welcomeMessage,
  });
}
