// This file is "model.dart"
// Will be generated by dart_mappable

import '../../domain/entity/provider_service_entity.dart';
import 'package:dart_mappable/dart_mappable.dart';

part 'hotel_model.mapper.dart';

@MappableClass()
class HotelModel extends ProviderServiceViewEntity with HotelModelMappable {
  HotelModel({
    @MappableField(key: 'item_id') required super.itemId,
    @MappableField(key: 'item_name')required super.itemName,
    @MappableField(key: 'item_description')required super.itemDescription,
    required super.price,
    required super.image,
    @MappableField(key: 'item_created_at') required super.itemCreatedAt,
    @MappableField(key: 'provider_id') required super.providerId,
    @MappableField(key: 'auth_id')required super.authId,
    @MappableField(key: 'provider_name') required super.providerName,
    required super.email,
    required super.phone,
    required super.location,
    @MappableField(key: 'commercial_register')required super.commercialRegister,
    @MappableField(key: 'provider_created_at')required super.providerCreatedAt,
    @MappableField(key: 'service_type_id') required super.serviceTypeId,
    @MappableField(key: 'location_url') super.locationUrl,
  });
}