// This file is "model.dart"
import 'package:dart_mappable/dart_mappable.dart';
import 'package:rifq/features/owner_flow/hotel/sup_feauter/payment/domain/entity/payment_entity.dart';

import '../../../../../../../core/shared/enum/status_payment_enum.dart';

// Will be generated by dart_mappable
part 'payment_model.mapper.dart';

@MappableClass()
class PaymentModel extends PaymentEntity with PaymentModelMappable {

  PaymentModel({
   required super.id,
    @MappableField(key: 'user_id')required super.userId,
    required super.context,
    @MappableField(key: 'context_id')required super.contextId,
    required super.amount,
    required super.status,
    @MappableField(key: 'created_at') required super.createdAt}

      );
}