// This file is "model.dart"
import 'package:dart_mappable/dart_mappable.dart';
import 'package:rifq/features/owner_flow/profile/domain/entities/user_profile_entity.dart';

// Will be generated by dart_mappable
part 'user_profile_model.mapper.dart';

@MappableClass()
class UserProfileModel extends UserProfileEntity with UserProfileModelMappable {

  UserProfileModel({
    required super.id,
    @MappableField(key: 'auth_id') required super.authId,
    required super.name,
    required super.email,
    @MappableField(key: 'created_at') required super.createdAt
  });
}