// This file is "model.dart"
import 'package:dart_mappable/dart_mappable.dart';
import 'package:rifq/features/owner_flow/profile/domain/entities/user_profile_entity.dart';

import '../../domain/entity/pet_profile_entity.dart';

// Will be generated by dart_mappable
part 'pet_profile_model.mapper.dart';

@MappableClass()
class PetProfileModel extends PetProfileEntity with PetProfileModelMappable {
 PetProfileModel({
   required super.id,
    required super.name,
    required super.breed,
    required super.species,
    required super.birthdate,
    required super.photoUrl,
  @MappableField(key: 'owner_id') required super.ownerId,
    required super.gender,
  @MappableField(key: 'created_at')required super.createdAt});
}