// This file is "model.dart"
import 'package:dart_mappable/dart_mappable.dart';
import 'package:rifq/features/owner_flow/profile/domain/entities/user_profile_entity.dart';

import '../../domain/entity/pet_profile_entity.dart';

// Will be generated by dart_mappable
part 'pet_profile_model.mapper.dart';

@MappableClass()
class UserProfileModel extends PetProfileEntity with UserProfileModelMappable {
  UserProfileModel({
   required super.id,
    required super.name,
    required super.breed,
    required super.species,
    required super.birthdate,
    required super.photoUrl,
    required super.ownerId,
    required super.gender,
    required super.createdAt});
}