// This file is "model.dart"
import 'package:dart_mappable/dart_mappable.dart';
import '../../domain/entity/reservation_entity.dart';

// Will be generated by dart_mappable
part 'reservation_model.mapper.dart';

@MappableClass()
class ReservationModel extends ReservationEntity with ReservationModelMappable {
  ReservationModel({
   required super.id,
    required super.userId,
    required super.providerId,
    required super.serviceTypeId,
    required super.serviceItemId,
    required super.petId,
    required super.date,
    required super.startDate,
    required super.endDate,
    required super.status,
    required super.notes,
    required super.createdAt});
}