// This file is "model.dart"
import 'package:dart_mappable/dart_mappable.dart';
import '../../domain/entity/reservation_entity.dart';

// Will be generated by dart_mappable
part 'reservation_model.mapper.dart';

@MappableClass()
class ReservationModel extends ReservationEntity with ReservationModelMappable {
  ReservationModel({
   required super.id,
   @MappableField(key: 'user_id') required super.userId,
   @MappableField(key: 'provider_id')required super.providerId,
   @MappableField(key: 'service_type_id') required super.serviceTypeId,
   @MappableField(key: 'service_item_id') required super.serviceItemId,
   @MappableField(key: 'pet_id')required super.petId,
    required super.date,
   @MappableField(key: 'start_date')required super.startDate,
   @MappableField(key: 'end_date')required super.endDate,
    required super.status,
    required super.notes,
   @MappableField(key: 'created_at')required super.createdAt});
}