// This file is "model.dart"
import 'package:dart_mappable/dart_mappable.dart';
import '../../domain/entity/health_record_entity.dart';

// Will be generated by dart_mappable
part 'health_record_model.mapper.dart';

@MappableClass()
@MappableClass()
class HealthRecordModel extends HealthRecordEntity with HealthRecordModelMappable {
  HealthRecordModel({
    required super.id,
    @MappableField(key: 'pet_id')required super.petId,
    required super.type,
    required super.title,
    required super.description,
    required super.date,
    @MappableField(key: 'clinic_name')required super.clinicName
  });

  /// fromMapا
  factory HealthRecordModel.fromMap(Map<String, dynamic> map) {
    return HealthRecordModel(
      id: map['id'],
      petId: map['pet_id'],
      type: map['type'],
      title: map['title'],
      description: map['description'],
      date: DateTime.parse(map['date']),
      clinicName: map['clinic_name'],
    );
  }

  HealthRecordEntity toEntity() {
    return HealthRecordEntity(
      id: id,
      petId: petId,
      type: type,
      title: title,
      description: description,
      date: date,
      clinicName: clinicName,
    );
  }
}





