// This file is "model.dart"
import 'package:dart_mappable/dart_mappable.dart';
import '../../domain/entity/health_record_entity.dart';

// Will be generated by dart_mappable
part 'health_record_model.mapper.dart';

@MappableClass()
@MappableClass()
class HealthRecordModel extends HealthRecordEntity with HealthRecordModelMappable {
  HealthRecordModel({
    required super.id,
    @MappableField(key: 'pet_id')required super.petId,
    required super.type,
     super.title,
     super.description,
     super.date,
    @MappableField(key: 'clinic_name') super.clinicName
  });

  /// fromMapا
  // factory HealthRecordModel.fromMap(Map<String, dynamic> map) {
  //   return HealthRecordModel(
  //     id: map['id'],
  //     petId: map['pet_id'] as String? ?? '',
  //     // petId: map['pet_id'],
  //     // type: map['type'],
  //     type: map['type'] as String,
  //
  //     title: map['title']as String?,
  //     description: map['description'] as String?,
  //     // date: DateTime.parse(map['date']),
  //     date: map['date'] != null
  //         ? DateTime.parse(map['date'] as String)
  //         : DateTime.now(),
  //     clinicName: map['clinic_name'] as String?,
  //   );
  // }
  factory HealthRecordModel.fromMap(Map<String, dynamic> map) {
    return HealthRecordModel(
      id: map['id'] as String? ?? '',
      petId: map['pet_id'] as String? ?? '',
      type: map['type'] as String? ?? '',
      title: map['title'] as String?,
      description: map['description'] as String?,
      date: map['date'] != null
          ? DateTime.parse(map['date'] as String)
          : null,
      clinicName: map['clinic_name'] as String?,
    );
  }

  HealthRecordEntity toEntity() {
    return HealthRecordEntity(
      id: id,
      petId: petId,
      type: type,
      title: title,
      description: description,
      date: date,
      clinicName: clinicName,
    );
  }
}





