// This file is "model.dart"
import 'package:dart_mappable/dart_mappable.dart';
import '../../domain/entity/reservation_entity.dart';

// Will be generated by dart_mappable
part 'reservation_model.mapper.dart';

@MappableClass()
class ReservationModel extends ReservationEntity with ReservationModelMappable {
 ReservationModel({
  required super.id,
  @MappableField(key: 'user_id') required super.userId,
  @MappableField(key: 'provider_id') required super.providerId,
  @MappableField(key: 'service_item_id') required super.serviceItemId,
  @MappableField(key: 'pet_id') required super.petId,
   super.time,
  @MappableField(key: 'start_date') required super.startDate,
  @MappableField(key: 'end_date') required super.endDate,
  required super.status,
   super.notes,
  @MappableField(key: 'created_at') required super.createdAt,
 });



 factory ReservationModel.fromMap(Map<String, dynamic> map) {
  return ReservationModel(
   id: map['id'] as String? ?? '',
   userId: map['user_id'] as String? ?? '',
   providerId: map['provider_id'] as String? ?? '',
   serviceItemId: map['service_item_id'] as String? ?? '',
   petId: map['pet_id'] as String? ?? '',
   time: map['time'] as String?,
   startDate: map['start_date'] != null
       ? DateTime.parse(map['start_date'] as String)
       : DateTime.now(),
   endDate: map['end_date'] != null
       ? DateTime.parse(map['end_date'] as String)
       : DateTime.now(),
   status: map['status'] as String? ?? 'pending',
   notes: map['notes'] as String?,
   createdAt: map['created_at'] != null
       ? DateTime.parse(map['created_at'] as String)
       : DateTime.now(),
  );
 }

 /// تحويل Model إلى Entity
 ReservationEntity toEntity() {
  return ReservationEntity(
   id: id,
   userId: userId,
   providerId: providerId,
   serviceItemId: serviceItemId,
   petId: petId,
   time: time,
   startDate: startDate,
   endDate: endDate,
   status: status,
   notes: notes,
   createdAt: createdAt,
  );
 }
}
