// This file is "model.dart"
import 'package:dart_mappable/dart_mappable.dart';
import '../../domain/entity/reservation_entity.dart';

// Will be generated by dart_mappable
part 'reservation_model.mapper.dart';

@MappableClass()
class ReservationModel extends ReservationEntity with ReservationModelMappable {
 ReservationModel({
  required super.id,
  @MappableField(key: 'user_id') required super.userId,
  @MappableField(key: 'provider_id') required super.providerId,
  @MappableField(key: 'service_item_id') required super.serviceItemId,
  @MappableField(key: 'pet_id') required super.petId,
   super.time,
  @MappableField(key: 'start_date') required super.startDate,
  @MappableField(key: 'end_date') required super.endDate,
  required super.status,
   super.notes,
  @MappableField(key: 'created_at') required super.createdAt,
 });

 /// Factory لتحويل Map (JSON) إلى ReservationModel
 factory ReservationModel.fromMap(Map<String, dynamic> map) {
  return ReservationModel(
   id: map['id'],
   userId: map['user_id'],
   providerId: map['provider_id'],
   serviceItemId: map['service_item_id'],
   petId: map['pet_id'],
   time: map['time'],
   startDate: DateTime.parse(map['start_date']),
   endDate: DateTime.parse(map['end_date']),
   status: map['status'],
   notes: map['notes'] as String?,
   createdAt: DateTime.parse(map['created_at']),
  );
 }

 /// تحويل Model إلى Entity
 ReservationEntity toEntity() {
  return ReservationEntity(
   id: id,
   userId: userId,
   providerId: providerId,
   serviceItemId: serviceItemId,
   petId: petId,
   time: time,
   startDate: startDate,
   endDate: endDate,
   status: status,
   notes: notes,
   createdAt: createdAt,
  );
 }
}
