// // This file is "model.dart"
// import 'package:dart_mappable/dart_mappable.dart';
// import '../../domain/entity/reservation_entity.dart';
//
// // Will be generated by dart_mappable
// part 'reservation_model.mapper.dart';
//
// @MappableClass()
// class ReservationModel extends ReservationEntity with ReservationModelMappable {
//   ReservationModel({
//    required super.id,
//    @MappableField(key: 'user_id') required super.userId,
//    @MappableField(key: 'provider_id')required super.providerId,
//    @MappableField(key: 'service_type_id') required super.serviceTypeId,
//    @MappableField(key: 'service_item_id') required super.serviceItemId,
//    @MappableField(key: 'pet_id')required super.petId,
//     required super.date,
//    @MappableField(key: 'start_date')required super.startDate,
//    @MappableField(key: 'end_date')required super.endDate,
//     required super.status,
//     required super.notes,
//    @MappableField(key: 'created_at')required super.createdAt});
// }
//
// extension ReservationModelX on ReservationModel {
//  ReservationEntity toEntity() {
//   return ReservationEntity(
//    id: id,
//    userId: userId,
//    providerId: providerId,
//    serviceTypeId: serviceTypeId,
//    serviceItemId: serviceItemId,
//    petId: petId,
//    date: date,
//    startDate: startDate,
//    endDate: endDate,
//    status: status,
//    notes: notes,
//    createdAt: createdAt,
//   );
//  }
// }


// This file is "model.dart"
import 'package:dart_mappable/dart_mappable.dart';
import '../../domain/entity/reservation_entity.dart';

// Will be generated by dart_mappable
part 'reservation_model.mapper.dart';

@MappableClass()
class ReservationModel extends ReservationEntity with ReservationModelMappable {
 ReservationModel({
  required super.id,
  @MappableField(key: 'user_id') required super.userId,
  @MappableField(key: 'provider_id') required super.providerId,
  @MappableField(key: 'service_type_id') required super.serviceTypeId,
  @MappableField(key: 'service_item_id') required super.serviceItemId,
  @MappableField(key: 'pet_id') required super.petId,
  required super.date,
  @MappableField(key: 'start_date') required super.startDate,
  @MappableField(key: 'end_date') required super.endDate,
  required super.status,
  required super.notes,
  @MappableField(key: 'created_at') required super.createdAt,
 });

 /// Factory لتحويل Map (JSON) إلى ReservationModel
 factory ReservationModel.fromMap(Map<String, dynamic> map) {
  return ReservationModel(
   id: map['id'],
   userId: map['user_id'],
   providerId: map['provider_id'],
   serviceTypeId: map['service_type_id'],
   serviceItemId: map['service_item_id'],
   petId: map['pet_id'],
   date: DateTime.parse(map['date']),
   startDate: DateTime.parse(map['start_date']),
   endDate: DateTime.parse(map['end_date']),
   status: map['status'],
   notes: map['notes'],
   createdAt: DateTime.parse(map['created_at']),
  );
 }

 /// تحويل Model إلى Entity
 ReservationEntity toEntity() {
  return ReservationEntity(
   id: id,
   userId: userId,
   providerId: providerId,
   serviceTypeId: serviceTypeId,
   serviceItemId: serviceItemId,
   petId: petId,
   date: date,
   startDate: startDate,
   endDate: endDate,
   status: status,
   notes: notes,
   createdAt: createdAt,
  );
 }
}
