// This file is "provider_profile_model.dart"
import 'package:dart_mappable/dart_mappable.dart';
import 'package:rifq/features/services_provider_flow/profile/domain/entities/provider_profile_entity.dart';

// Will be generated by dart_mappable
part 'provider_profile_model.mapper.dart';

@MappableClass()
class ProviderProfileModel extends ProviderProfileEntity
    with ProviderProfileModelMappable {
  ProviderProfileModel({
    required super.id,
    @MappableField(key: 'auth_id') required super.authId,
    required super.name,
    required super.email,
    required super.phone,
    required super.location,
    @MappableField(key: 'commercial_register')
    required super.commercialRegister,
    @MappableField(key: 'location_url') required super.locationUrl,
    super.image,
    @MappableField(key: 'created_at') required super.createdAt,
  });
}
