// This file is "model.dart"
import 'package:dart_mappable/dart_mappable.dart';
import '../../domain/entity/health_record_entity.dart';

// Will be generated by dart_mappable
part 'health_record_model.mapper.dart';

@MappableClass()
class HealthRecordModel extends HealthRecordEntity with HealthRecordModelMappable {
  HealthRecordModel({
    required super.id,
    @MappableField(key: 'pet_id')required super.petId,
    required super.type,
    required super.title,
    required super.description,
    required super.date,
    @MappableField(key: 'clinic_name')required super.clinicName});
}


